import Navbar from "@/components/Navbar";
import "./globals.css";
import Providers from "./providers";
import localFont from "next/font/local";

export const metadata = {
  title: "Sieben.dev - Home",
  description: "Generated by create next app",
};

const hilmar = localFont({ src: "../assets/fonts/RNSPhysis-Medium.otf" });

export default function RootLayout({ children }) {
  return (
    <html className="max-w-[1000px] mx-auto p-12 duration-300" lang="en">
      <body className={`${hilmar.className} bg-[#45FFCA] dark:bg-black`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
